
export const FETCH_BLOG_POSTS = "FETCH_BLOG_POSTS";
export const POST_NEW_BLOG = "POST_NEW_BLOG";
export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST";
export const UPDATE_POST_VOTE = "UPDATE_POST_VOTE";
export const UPDATE_COMMENT_VOTE = "UPDATE_COMMENT_VOTE";
export const DELETE_SINGLE_POST = "DELETE_SINGLE_POST";
export const FETCH_POST_COMMENTS = "FETCH_POST_COMMENTS";
export const POST_NEW_COMMENT = "POST_NEW_COMMENT";
export const DELETE_SINGLE_COMMENT = "DELETE_SINGLE_COMMENT";
export const EDIT_SINGLE_POST = "EDIT_SINGLE_POST";
export const EDIT_SINGLE_COMMENT = "EDIT_SINGLE_COMMENT";
export const FETCH_SINGLE_COMMENT = "FETCH_SINGLE_COMMENT";